[tool.black]
line-length = 99
target-version = ['py36']

[tool.ruff]
line-length = 120
# Enable Pyflakes `E` and `F` codes by default.
lint.select = [
  "E",
  # see: https://pypi.org/project/pycodestyle
  "W",
  # see: https://pypi.org/project/pyflakes
  "F",
  # see: isort
  "I",
]
lint.ignore = ["E501"]
lint.ignore-init-module-imports = true
lint.unfixable = ["F401"]

